package org.tempuri;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-11-14T13:47:09.331+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "CommServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface CommServiceHttpPost {
}
